apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-06T01:54:39Z"
  generateName: todo1-77b88ffbf9-
  labels:
    app: todo1
    pod-template-hash: 77b88ffbf9
  name: todo1-77b88ffbf9-7mcf2
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: todo1-77b88ffbf9
    uid: 051d9f5b-5fff-429b-b99c-9808467cc989
  resourceVersion: "2398970"
  uid: 58bb9a33-bf9e-451b-8d33-9d6a873976b0
spec:
  containers:
  - image: nkw12345/todo:0.1
    imagePullPolicy: IfNotPresent
    name: todo
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6ssfn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-6ssfn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-10-06T01:54:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-10-06T06:48:50Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-10-06T06:48:50Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-10-06T01:54:39Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://120e1a96a030da4e5785266e1b70c266aabe5f6d709f7e413c6769356921ae9e
    image: docker.io/nkw12345/todo:0.1
    imageID: docker.io/nkw12345/todo@sha256:0d95e20fdc9dfbf95b655de3b7bdc01e56af7b97b9520676408c5fbcaf4c5869
    lastState:
      terminated:
        containerID: containerd://3c1dc81a64534d90d917f113fb6dcc82e21745c72ea3f0783319a4f7bae4a1dd
        exitCode: 255
        finishedAt: "2023-10-06T06:48:26Z"
        reason: Unknown
        startedAt: "2023-10-06T01:54:39Z"
    name: todo
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2023-10-06T06:48:49Z"
  hostIP: 172.16.1.91
  phase: Running
  podIP: 10.32.0.6
  podIPs:
  - ip: 10.32.0.6
  qosClass: BestEffort
  startTime: "2023-10-06T01:54:39Z"
